- hosts: localhost
  vars:
  pre_tasks:
    - name: Update package mana
      become: true
      community.general.pacman:
        update_cache: true
      tags:
        - base
        - install
  tasks:
    - include: tasks/core-setup.yaml
    - include: tasks/desktop.yaml
  post_tasks:
    - name: clean up
      ansible.builtin.command:
        cmd: rm -rdf /tmp/paru
      become: true
      tags:
        - base
        - install
        - aur
