- name: ensure installed hyprland dependencies
  community.general.pacman:
    name: [ "gdb", "ninja", "gcc", "cmake", "meson", "libxcb", "xcb-proto", "xcb-util", "xcb-util-keysyms", "libxfixes", "libx11", "libxcomposite", "xorg-xinput", "libxrender", "pixman", "wayland-protocols", "cairo", "pango", "seatd", "libxkbcommon", "xcb-util-wm", "xorg-xwayland", "libinput", "libliftoff", "libdisplay-info", "cpio" ]
  tags:
    - install
    - hyprland
- name: install display manager (ly)
  community.general.pacman:
    name: [ "ly" ]
  tags:
    - install
    - hyprland
    - display_manager
- name: enable display manager (ly)
  ansible.builtin.service:
    name: ly
    state: started
    enable: true
- name: clone hyprland repository
  ansible.builtin.git:
    repo: git@github.com:hyprwm/Hyprland.git
    dest: /tmp/hyprland
    recursive: true
  tags:
    - install
    - hyprland
- name: make install hyprland
  community.general.make:
    chdir: /tmp/hyprland
    target: install
  become: true
  tags:
    - install
    - hyprland
